[package]
name = "hashboard"
version = "0.1.0"
authors = ["Sherwyn Sen <sherwyn.sen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
